### ISSUE TITLE
Docker image is generating with name "example-all"

### ISSUE THREAD

**Issue by mounikakella** [clayrisser/reactant#31]

**Comment by clayrisser** [comment]
This issue is your `.reactantrc` file was configured in the following way . . .
```yaml
platforms:
  web:
    image: image/name:latest
```

. . . and instead should have been configured in the following way
```yaml
platforms:
  web:
    docker:
      image: image/name:latest
```
